openvitae-tech/blackboard-lms

.github/workflows/rubyonrails.yml, Gemfile, Gemfile.lock
- Corrected platform for actions.
- Added missing Gemfile entries.
=> Fixed GH action configurations.

app/assets/stylesheets/application.tailwind.css, app/views/teams/_show_mobile.html.erb
focus ring color is given as primary also a margin is added at the top of a search bar in team's mobile view
=> Searchbar style corrections

README.md, bin/setup
=> Fixed `bin/setup` not creating `database.yml`

app/views/dashboards/_index_desktop.html.erb, app/views/dashboards/_index_mobile.html.erb, app/views/shared/components/_average_numof_video_assigned_chart.html.erb, app/views/shared/components/_average_time_spend_chart.html.erb, app/views/shared/components/_course_watch_time_chart.html.erb, app/views/shared/components/_enrolled_ratio_chart.html.erb, app/views/shared/components/_self_enrolled_ratio_chart.html.erb, app/views/shared/components/_team_progress_chart.html.erb, app/views/shared/components/_total_views_chart.html.erb
=> Verbiage fixes on the dashboard page

app/views/shared/components/_team_progress_chart.html.erb
=> dashboard graph alignment issue fix

config/tailwind.config.js
Text color #333333 is added to the color list of Tailwind config file
=> Text color added to the tailwind config file

app/assets/stylesheets/course.css.erb, app/views/shared/components/_course_description_card.html.erb
On course description box padding issue while showing less content is fixed ,
Fixes #51
=> Course description box alignment while show less and more fixes

app/views/devise/mailer/course_assign_email.html.erb, app/views/devise/mailer/course_started_email.html.erb
Email template for Assign course ,
for the user letting know that one course is assigned to him  and once the user Strats with the course, the manager will be informed with an another Email.
=> Email template for Assign course

app/controllers/invites_controller.rb, app/models/user.rb, app/policies/invite_policy.rb, app/services/user_management_service.rb, app/views/invites/create.turbo_stream.erb, app/views/invites/new.html.erb, app/views/invites/resend.html.erb, app/views/invites/resend.turbo_stream.erb, app/views/learning_partners/show.html.erb, app/views/shared/components/_file_select.html.erb, app/views/shared/components/_flash.html.erb, app/views/shared/components/_modal_flash.html.erb, app/views/shared/components/_notice.html.erb, app/views/shared/components/_notice_error.html.erb, app/views/shared/components/_notice_success.html.erb, app/views/teams/_member_desktop.html.erb, app/views/teams/_member_list.erb, app/views/teams/_member_list_mobile.html.erb, app/views/teams/_member_mobile.html.erb, app/views/teams/_show_desktop.html.erb, config/locales/en.yml, config/routes.rb
=> Bulk invite

app/models/user.rb, app/services/login_with_otp_service.rb, config/credentials.yml.enc.example, db/migrate/20241024095721_rename_otp_column_in_users.rb, db/schema.rb, spec/requests/login_with_mobile_spec.rb
Fixes #135 
Demo: https://paulsojan.neetorecord.com/watch/1c05ecf6-0030-4401-afaf-96ae8859690a
=> Created functionality to store OTP as hash in the DB

app/views/courses/_form.html.erb, app/views/courses/_index_desktop.html.erb, app/views/courses/_show_desktop.html.erb, app/views/courses/edit.html.erb, app/views/courses/new.html.erb, app/views/lessons/_form.html.erb, app/views/lessons/edit.html.erb, app/views/shared/components/_course_description_card.html.erb, app/views/shared/components/_course_lessons.html.erb, app/views/shared/components/_default_button.html.erb
Add course pages modifications 
pages are done unto now is listed here
two more pages remains
=> Admin course add page modification changes

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/teams_controller.rb, app/helpers/users_helper.rb, app/models/team.rb, app/policies/invite_policy.rb, app/policies/team_policy.rb, app/views/invites/new.html.erb, app/views/shared/components/_sidebar_desktop.html.erb, app/views/shared/components/_sidebar_mobile.html.erb
Fix policies for creating resources within team
Fixes #165
=> Restrict learners from going to team page

.gitignore, .husky/pre-commit, .rubocop.yml, Gemfile, Gemfile.lock, lib/tasks/rubocop.rake
=> Add rubocop and precommit hooks to run rubocop using husky

app/models/course.rb, app/policies/course_policy.rb, app/views/courses/_show_desktop.html.erb, app/views/shared/components/_outline_button_danger.html.erb, spec/requests/courses/destroy_spec.rb
=> Allow admin users to delete an unpublished course having zero enrollment

app/javascript/controllers/otp_controller.js, app/views/logins/_otp_desktop.html.erb, app/views/logins/_otp_mobile.html.erb
When we input a digit in each box in otp input screen. The focus  shifts from one input box to next. When we delete a digit the focus shifts to previous box.
The button becomes active when all four boxes are full.
Fixes #123
=> Otp filed modification

app/views/courses/_course_description_card.html.erb, app/views/courses/_course_lessons.html.erb, app/views/courses/_show_desktop.html.erb
=> Course page UI bug fix

app/javascript/controllers/otp_controller.js
=> Added a Auto focus on first field of the OTP input field

config/routes.rb
=> Fixed getting user not signed in toastr upon hitting root url

app/views/teams/_sub_teams.html.erb, app/views/teams/_sub_teams_mobile.html.erb, app/views/teams/_team_desktop.html.erb, app/views/teams/_team_mobile.html.erb
=> Team list implemented as a div changed to list(ul), with vertical scrollbar

.husky/pre-commit, README.md, docker-compose.yml
=> Add redis to docker compose 

app/javascript/controllers/forms_controller.js, app/services/user_management_service.rb
Implement a check to ensure that the selected file is a CSV file before allowing the upload .
Fixes  #148
=> Csv file check

app/controllers/application_controller.rb, app/views/pages/not_found.html.erb, config/routes.rb, config/routes/catch_all.rb, spec/requests/application_controller_spec.rb
=> Render 404 page

Gemfile, Gemfile.lock, config/initializers/bullet.rb
=> Added bullet gem

.dockerignore, Dockerfile, README.md, config/sidekiq.yml, docker-compose.yml
=> Update docker-compose.yml with sidekiq worker

app/views/course_modules/_form.html.erb, app/views/courses/_form.html.erb, app/views/lessons/edit.html.erb
Fixes #241 
Demo: https://paulsojan.neetorecord.com/watch/4759b2c4-d25e-40fd-9edd-bdd3e19de91c
=> Fixed cancel button link issue

app/controllers/courses_controller.rb, app/controllers/users_controller.rb, app/models/course.rb, app/models/course_module.rb, app/models/enrollment.rb, app/models/lesson.rb, app/views/courses/_course_card_with_left_image.html.erb, app/views/courses/_course_card_with_top_image.html.erb, app/views/courses/_course_description_card.html.erb, app/views/courses/_course_description_card_mobile.html.erb, app/views/courses/_course_lessons_mobile.html.erb, app/views/courses/_index_desktop.html.erb, app/views/courses/_index_mobile.html.erb, app/views/courses/_show_desktop.html.erb, app/views/courses/_show_mobile.html.erb, app/views/lessons/_play_list.html.erb, app/views/lessons/_play_list_mobile.html.erb, app/views/shared/components/_progress_bar.html.erb, app/views/users/_show_desktop.html.erb
=> Show course and module progres with real values

app/helpers/application_helper.rb, app/views/lessons/_play_list_mobile.html.erb, app/views/shared/components/_sidebar_desktop.html.erb, app/views/shared/components/_sidebar_mobile.html.erb
=> Show sidebar link as selected if user clicks on the link

app/helpers/application_helper.rb, app/helpers/courses_helper.rb, app/views/lessons/_play_list.html.erb, app/views/lessons/_play_list_mobile.html.erb
=> Implemented showing lesson duration

app/javascript/controllers/video_upload_controller.js, app/views/lessons/add_edit/_add_local_content.html.erb
=> Fixed video being send to backend upon creating the lesson

spec/requests/course_modules_controller_spec.rb
=> Added request spec for course module

app/views/shared/components/_navbar_desktop.html.erb
=> On header box shadow is removed as it is effecting all the sides

app/views/quizzes/_form.html.erb, app/views/quizzes/_quiz_submit_form.html.erb
=> radio button alignment issue fixed

db/seeds.rb
=> Fixed course banner not getting attached with seed data

app/assets/stylesheets/application.tailwind.css, app/helpers/courses_helper.rb, app/policies/course_policy.rb, app/policies/lesson_policy.rb, app/policies/quiz_policy.rb, app/services/course_management_service.rb, app/views/course_modules/show.html.erb, app/views/courses/_course_lessons.html.erb, app/views/courses/_course_lessons_mobile.html.erb, app/views/courses/_show_desktop.html.erb, app/views/courses/_show_mobile.html.erb, app/views/lessons/_play_list.html.erb, app/views/lessons/_play_list_mobile.html.erb, app/views/lessons/_show_desktop.html.erb, app/views/lessons/_show_mobile.html.erb, app/views/quizzes/_show_desktop.html.erb, app/views/shared/components/_bread_crumbs.html.erb
Fixes #220 , #270, #183
- Highlight current module and current lesson
- Show lesson title as page heading in lesson page
- Disable unenroll in production
- Update delete policies for quiz and lessons
- Prevent updating progress of a completed lesson
=> Misc fixes 3

app/controllers/invites_controller.rb, app/helpers/users_helper.rb, app/models/course.rb, app/models/user.rb, app/services/bulk_invite_input_service.rb, app/services/user_management_service.rb, app/views/invites/learner_bulk_invite_sample.csv, app/views/invites/new.html.erb, app/views/user_mailer/course_assignment.html.erb, config/routes.rb, spec/fixtures/files/invalid_bulk_invite.csv, spec/fixtures/files/valid_bulk_invite.csv, spec/requests/courses/update_spec.rb, spec/requests/user_invite_spec.rb
Provide a sample csv while inviting learners in bulk
=> Accept name while inviting a new user.

app/assets/stylesheets/course.css.erb, app/views/courses/_course_description_card.html.erb, app/views/shared/components/_button_primary_small.html.erb, app/views/shared/components/_desktop_layout.html.erb, app/views/shared/components/_icon_button_primary_small.html.erb
padding and button alignment is fixed 
Fixes #282 ,  #296
=> course details page issues fix

app/assets/icons/down_arrow_green.svg, app/assets/icons/up_arrow_green.svg, app/assets/stylesheets/course.css.erb, app/assets/stylesheets/course_progress.css, app/assets/stylesheets/icons.css.erb, app/javascript/controllers/course_description_card_controller.js, app/views/courses/_course_description_card.html.erb, app/views/courses/_show_mobile.html.erb, app/views/lessons/_play_list.html.erb, app/views/lessons/_show_mobile.html.erb, app/views/lessons/_video_frame.html.erb, app/views/lessons/_video_frame_mobile.html.erb
Remove show more from course description card. 
Fixes #286
Add show more/show less to lessons details page 
Fixes #287
Sidebar list style is broken with too much space 
Fixes #323
=> show more and less removed from course details page and added to the lesson details page

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/icons.css.erb, app/views/shared/components/_sidebar_mobile.html.erb
Logout link is missing in the mobile UI 
Fixes #327
=> logout button added to mobile view also ,also hover effect is added to the button

app/views/courses/_index_desktop.html.erb, app/views/courses/_index_mobile.html.erb
In the course page enrolled course and available course added some gaps in between 
Fixes #303
=> margin added before and after enrolled courses

app/models/local_content.rb
=> Add Telugu and Assamese to the list of languages

app/javascript/controllers/notice_controller.js
=> Remove notice after 2 seconds

app/helpers/courses_helper.rb
=> Fix the course banner resolution

app/views/devise/mailer/confirmation_instructions.html.erb
Email not showing properly in mobile view 
Fixes #320
=> email template changes

app/views/devise/mailer/course_started_email.html.erb, app/views/user_mailer/course_assignment.html.erb
Email template for Assign course is modified
=> assign course email is reworked

app/views/settings/_page_body.html.erb, app/views/settings/_page_header.html.erb, app/views/settings/_show_desktop.html.erb, app/views/settings/_show_mobile.html.erb, config/tailwind.config.js
User settings profile- User image added also some padding issue 
Fixes #359
=> Add user profile image

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/layouts/devise.html.erb
Change title to Instruo 
Fixes #370
=> web app title changed

app/views/course_assigns/_course_card.html.erb, app/views/course_assigns/_course_card_mobile.html.erb, app/views/course_assigns/_new_mobile.html.erb, app/views/courses/_course_card_with_left_image.html.erb, app/views/courses/_course_card_with_top_image.html.erb, app/views/courses/_course_description_card.html.erb, app/views/courses/_course_description_card_mobile.html.erb, app/views/shared/components/_progress_bar.html.erb
Fix UI in course page
Fixes #349
=> course cards paddings adjusted

app/views/shared/components/_icon_button_primary_small.html.erb, app/views/shared/components/_outline_icon_button_secondary_small.html.erb
Adjust buttons padding and line height 
Fixes #382
=> primary small and secondary small buttons with icons padding and line height adjustments

app/controllers/course_assigns_controller.rb, app/errors/errors.rb, app/models/course.rb, app/models/team.rb, app/models/team_enrollment.rb, app/models/user.rb, app/policies/course_assigns_policy.rb, app/services/course_management_service.rb, app/views/teams/_member_desktop.html.erb, app/views/teams/_member_mobile.html.erb, db/migrate/20241206070707_create_team_enrollments.rb, db/migrate/20241206073351_add_team_enrollments_count_to_teams.rb, db/migrate/20241206073632_add_assigned_by_to_team_enrollents.rb, db/migrate/20241206074129_add_team_enrollments_count_to_courses.rb, db/schema.rb, spec/requests/course_assigns/create_spec.rb, spec/requests/course_assigns/new_spec.rb, spec/requests/courses/enroll_spec.rb
=> course asignment checks

app/controllers/courses_controller.rb, app/helpers/courses_helper.rb, app/queries/user_enrolled_query.rb, app/services/course_management_service.rb, app/services/event_service.rb, app/value_objects/partner_metrics.rb, spec/factories.rb
=> Show correct enrollment counts in the course listing

app/views/course_assigns/_new_mobile.html.erb, app/views/teams/_member_list_mobile.html.erb, app/views/teams/_show_mobile.html.erb
Invite user and assign course  button on mobile view needs improvements 
Fixes #385
=> Bottom fixed buttons improved

app/views/settings/_page_body.html.erb, app/views/settings/_page_header.html.erb, app/views/settings/_show_desktop.html.erb, app/views/settings/_show_mobile.html.erb
Improve User Settings Page Design and Structure 
Fixes #364
=> user page improvements

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/login.css.erb, app/views/shared/components/_navbar_desktop.html.erb
Drop shadow missing on the Nav bar 
Fixes #350
=> Border removed and box shadow added to nav bar

app/jobs/course_deadline_reminder_job.rb, app/mailers/user_mailer.rb, app/views/user_mailer/course_deadline_reminder.html.erb, config/scheduled_jobs.yml, db/migrate/20241209110404_reminder_send_at_to_enrollments.rb, db/schema.rb
=> Schedule daily cron job to send email alerts for course deadline.

app/controllers/courses_controller.rb, db/migrate/20241209115158_course_started_at_to_enrollments.rb, db/schema.rb
=> Publish course started event only once.

app/views/settings/_page_body.html.erb, app/views/settings/_show_desktop.html.erb, app/views/settings/_show_mobile.html.erb, app/views/shared/components/_navbar_mobile.html.erb, app/views/shared/components/_profile_pic.html.erb, app/views/teams/_member_mobile.html.erb
=> user profile pic issue fixed

app/views/shared/components/_icon_button_primary.html.erb, app/views/shared/components/_sidebar_desktop.html.erb, app/views/tags/index.html.erb
=> icons added for tag and add tag

app/views/courses/_show_desktop.html.erb
Button alignment issue in course module page 
Fixes #417
=> Button allignment issue at admin course page resolved

app/views/course_modules/show.html.erb, app/views/courses/_index_desktop.html.erb, app/views/courses/_show_desktop.html.erb, app/views/learning_partners/index.html.erb, app/views/learning_partners/show.html.erb, app/views/shared/components/_button_primary_sticky_bottom.html.erb, app/views/shared/components/_icon_button_primary.html.erb, app/views/shared/components/_icon_button_secondary.html.erb, app/views/shared/components/_label_medium_notice.html.erb, app/views/shared/components/_label_medium_success.html.erb, app/views/shared/components/_outline_icon_button_primary.html.erb, app/views/teams/_member_desktop.html.erb, app/views/teams/_member_mobile.html.erb, app/views/teams/_show_mobile.html.erb, app/views/teams/_sub_teams.html.erb, app/views/teams/_sub_teams_mobile.html.erb, app/views/teams/_team_actions.html.erb
A few changes done to fix some issues with icons after adaptation
=> A few issues with icon adaptation has been fixed

app/views/shared/components/_alert.html.erb, app/views/tags/edit.html.erb, app/views/tags/new.html.erb
=> Color added for close icon in tags page's components

app/views/shared/components/_navbar.html.erb
profile pic and notification is misaligned at the web navbar
Fix #436
=> profile pic and notification misalignment issue fixed

app/assets/stylesheets/application.tailwind.css, app/views/settings/_page_header.html.erb, app/views/shared/components/_navbar.html.erb, app/views/shared/components/_navbar_desktop.html.erb, app/views/shared/components/_navbar_mobile.html.erb, app/views/shared/components/_profile_pic.html.erb, app/views/shared/components/_sidebar.html.erb
=> Fix navbar in the new layout

db/seeds.rb
=> Updated tag seed data

app/controllers/learning_partners_controller.rb, app/models/event.rb, app/queries/course_completed_query.rb, app/queries/course_views_query.rb, app/queries/first_owner_joined_query.rb, app/queries/lesson_views_query.rb, app/queries/onboarding_completed_query.rb, app/queries/onboarding_initiated_query.rb, app/queries/time_spent_query.rb, app/queries/user_invited_query.rb, app/queries/user_joined_query.rb, app/queries/user_login_query.rb, app/queries/user_logout_query.rb, app/value_objects/partner_metrics.rb, app/views/learning_partners/show.html.erb
=> Show important partner metrics on the partner page

app/views/settings/_page_header.html.erb
=> Fix user icon for admin view in user/settings page

app/services/vimeo/upload_video_service.rb
=> Fixed streaming chunks of the file to Vimeo instead of loading the entire file into memory

app/views/notifications/_count_value.html.erb, app/views/notifications/_list.html.erb, app/views/notifications/_notification.html.erb, app/views/shared/components/_navbar.html.erb
=> Scrolling added to notification list and some other fixes

app/views/shared/components/_navbar.html.erb
=> Notification list added to the navbar

app/views/learning_partners/_form.html.erb, app/views/learning_partners/edit.html.erb, app/views/learning_partners/index.html.erb, app/views/learning_partners/new.html.erb, app/views/learning_partners/show.html.erb
=> partner pages in single layout is done

app/assets/stylesheets/application.tailwind.css, app/controllers/teams_controller.rb, app/models/team.rb, app/views/teams/_form.html.erb, app/views/teams/_team_card.html.erb, db/migrate/20250109083052_add_department_to_teams.rb, db/schema.rb, spec/requests/teams_spec.rb
=> Add department to team

app/assets/stylesheets/application.tailwind.css, app/views/course_modules/_form.html.erb, app/views/course_modules/edit.html.erb, app/views/course_modules/new.html.erb, app/views/course_modules/show.html.erb, app/views/courses/_form.html.erb, app/views/courses/edit.html.erb, app/views/courses/new.html.erb, app/views/lessons/_form.html.erb, app/views/lessons/edit.html.erb, app/views/lessons/new.html.erb, app/views/quizzes/_form.html.erb, app/views/quizzes/edit.html.erb, app/views/quizzes/new.html.erb, app/views/quizzes/show.html.erb, app/views/shared/components/_bread_crumbs.html.erb
Admin-course pages modification after converted to single layout 
Fixes #506
=> Admin course changes in singlelayout

app/views/courses/_course_card_with_top_image.html.erb, app/views/shared/components/_progress_bar_short.html.erb
=> New course card changes are done

app/helpers/application_helper.rb, app/javascript/controllers/notifications_controller.js, app/views/notifications/_notification.html.erb
=> Increase notification poling interval in local

app/views/course_modules/_form.html.erb
=> Fix cancel button issue on module edit page

app/helpers/teams_helper.rb, app/views/course_modules/show.html.erb, app/views/courses/show.html.erb, app/views/lessons/show.html.erb, app/views/shared/components/_bread_crumbs.html.erb, app/views/teams/_page_header.html.erb
=> Show breadcrumbs with a title

app/models/lesson.rb, config/locales/en.yml, spec/models/lesson_spec.rb
=> Added validation for lesson duration

app/views/dashboards/_team_progress_chart_mobile.html.erb
Removed mobile  file from dashboard directory 
Fixes #551
=> Removed unused mobile version file from dashboard directry

app/views/quizzes/_show_desktop.html.erb, app/views/quizzes/_show_mobile.html.erb
Remove mobile or desktop version files from Quizzes directory 
Fixes #555
=> Removed unused mobile nd desktop version file from quizzes directry

app/controllers/users_controller.rb, app/services/user_statistics_service.rb
=> Fix bug in calculating time spent by each user

app/javascript/controllers/sidebar_controller.js, app/views/shared/components/_navbar.html.erb, app/views/shared/components/_sidebar.html.erb
The pull out sidebar able to close when clicked outside. 
Fixes #558
=> Sidebar closing made possible even click on the oustside of the sidebar

app/views/courses/_course_card_with_top_image.html.erb, app/views/courses/index.html.erb
=> Restrict managers from accessing course from user profile page

app/controllers/courses_controller.rb, app/models/tag.rb
=> Set a limit for tag loading

app/models/course.rb, app/services/courses/filter_service.rb, spec/requests/courses/index_spec.rb
=> Set limits for course listing to 12 per page.

app/views/course_modules/show.html.erb, app/views/courses/show.html.erb, app/views/lessons/show.html.erb, app/views/shared/components/_bread_crumbs.html.erb, app/views/shared/components/_sidebar.html.erb, app/views/teams/_page_header.html.erb, config/locales/en.yml
=> Add links on breadcrumbs for main sections

app/views/courses/_course_description_card.html.erb, app/views/courses/index.html.erb, app/views/teams/_team_card.html.erb, app/views/users/show.html.erb, config/locales/en.yml
=> Text changes

app/views/shared/components/_dropdown_menu.html.erb
Dropdown list in home dash board is going out of the margin issue fixed 
fixes #598
=> Dropdown list in dashboard view out of the margin issue fixed

app/value_objects/dashboard.rb, app/views/dashboards/index.html.erb, app/views/teams/_page_header.html.erb
=> Fix manager dashboard, view team specific dashboard.

app/views/courses/_course_lessons.html.erb, app/views/quizzes/_quiz.html.erb, app/views/quizzes/_quiz_submit_form.html.erb
There is one color "black0" is removed as it is not available as well as not using it anywhere
Fixes  #616
=> Removed usage of Unavailbale color black0

app/views/devise/shared/_left_side_desktop.html.erb
=> Update bottom links in the login page

.husky/helpers/no_console.sh, .husky/pre-commit, app/javascript/controllers/course_description_card_controller.js, app/javascript/controllers/lessons_controller.js, app/javascript/controllers/modals_controller.js, app/javascript/controllers/otp_controller.js, app/javascript/controllers/teams_controller.js, app/javascript/controllers/user_status_confirmation_controller.js, package-lock.json
=> Added pre-commit hook to catch `console.log` from files

app/controllers/application_controller.rb, app/controllers/course_assigns_controller.rb, app/controllers/searches_controller.rb, app/javascript/controllers/searches_controller.js, app/models/search_context.rb, app/services/course_management_service.rb, app/services/courses/filter_service.rb, app/views/course_assigns/_course_card.html.erb, app/views/course_assigns/_course_list_with_assign_form.html.erb, app/views/course_assigns/create.turbo_stream.erb, app/views/course_assigns/new.html.erb, app/views/searches/_filters.html.erb, app/views/searches/_form.html.erb, app/views/searches/_selected_tags.html.erb, app/views/searches/index.turbo_stream.erb, app/views/teams/_member_list_items.html.erb, app/views/teams/_team_actions.html.erb, config/routes.rb, spec/requests/course_assigns/new_spec.rb
=> implement search and filter in assigns

app/controllers/commons/alert_modal_controller.rb, app/views/commons/alert_modal/show.html.erb, app/views/courses/show.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/commons/alert_modal_spec.rb
Fixes #285 
Demo: https://paulsojan.neetorecord.com/watch/c23afed6-010b-4c2f-9e3e-ffebdbc3c3a9
=> Added alert while deleting the course

app/assets/stylesheets/course_progress.css, app/views/quizzes/_quiz_submit_form.html.erb
Quiz Box Overflowing Beyond Navbar issue is fixed
Fixes #670
=> Quiz box overflowing issue fixed

app/helpers/lessons_helper.rb, app/views/lessons/_video_frame.html.erb
Fixes #664 
Demo: https://paulsojan.neetorecord.com/watch/580a1831-d566-414e-a155-ac645920ac7f
=> Fixed non-admins clicking the next button on the lessons show page should redirect to the course page if it’s the last lesson

app/views/courses/_course_card_with_top_image.html.erb
Course card in different heights is fixed
Fixes #643
=> Course card different height is fixed

app/assets/stylesheets/application.tailwind.css
=> Prevented Overflow in Rich Text Editor for Lesson Description

Gemfile, Gemfile.lock, app/views/learning_partners/show.html.erb
=> Show time spent in readable format

.gitignore, app/views/course_modules/show.html.erb, config/locales/en.yml
=> Fixed missing translation for the edit button on the course module page

app/views/course_assigns/_course_card.html.erb, app/views/courses/_course_card_with_top_image.html.erb, app/views/onboarding/welcomes/_progress.html.erb, config/tailwind.config.js
=> Added colour  "theme-highlight" in tailwind color codes. And Used this colour as label backgrund color for levels.

app/views/shared/components/_flash.html.erb
=> Fixed `success` and `error` flash not rendering

app/assets/icons/eye.svg, app/assets/stylesheets/application.css, app/assets/stylesheets/icons.css.erb, app/views/courses/_course_lessons.html.erb, app/views/shared/components/_outline_icon_button_small.html.erb
=>  Change "Edit Module" to "View Module" with Redirect & Correct Button Text Color to White

app/assets/stylesheets/course_progress.css, app/views/quizzes/_quiz.html.erb, app/views/quizzes/_quiz_submit_form.html.erb, app/views/quizzes/_quizz_box.html.erb
Inconsistent quiz box size due to varying question lengths is fixed 
Fixes #692
=> Inconsistent quiz box size fixed 

app/views/courses/_course_description_card.html.erb, app/views/courses/show.html.erb, app/views/shared/components/_icon_button_primary.html.erb, app/views/shared/components/_outline_button_danger.html.erb, config/locales/en.yml
=> Added tooltip

app/assets/icons/adjustments-vertical.svg, app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/icons.css.erb, app/controllers/ui/base_controller.rb, app/controllers/ui/buttons_controller.rb, app/controllers/ui/components_controller.rb, app/controllers/ui/icons_controller.rb, app/controllers/ui/inputs_controller.rb, app/controllers/ui/typography_controller.rb, app/helpers/settings_helper.rb, app/views/ui/buttons/_button.html.erb, app/views/ui/buttons/index.html.erb, app/views/ui/components/index.html.erb, app/views/ui/icons/index.html.erb, app/views/ui/inputs/index.html.erb, app/views/ui/typography/index.html.erb, config/locales/ui.en.yml, config/routes.rb, config/routes/ui.rb
=> Add provision for implementing/testing and viewing of ui components

app/controllers/learning_partners_controller.rb, app/errors/errors.rb, app/models/concerns/partner_state.rb, app/models/concerns/user_state.rb, app/models/learning_partner.rb, app/models/user.rb, app/policies/learning_partner_policy.rb, app/views/learning_partners/show.html.erb, config/routes.rb, spec/requests/course_modules_spec.rb, spec/requests/home_spec.rb, spec/requests/learning_partner_activate_deactivate_spec.rb, spec/requests/lessons_spec.rb, spec/requests/local_contents_spec.rb, spec/requests/scorms_spec.rb, spec/requests/settings_spec.rb, spec/requests/tags_spec.rb
=> 708 deactivate learning partner

app/controllers/quizzes_controller.rb, app/policies/quiz_policy.rb, app/services/course_management_service.rb, app/views/quizzes/_quiz.html.erb, app/views/quizzes/_quiz_submit_form.html.erb, app/views/quizzes/_quizz_box.html.erb
=> Fix quiz answer display for users

app/assets/stylesheets/application.tailwind.css, app/views/ui/typography/index.html.erb
=> Typography with sample text and classes table added

app/assets/stylesheets/course_progress.css, app/helpers/ui_helper.rb, app/views/ui/components/index.html.erb, app/views/ui/inputs/_dropdown_field.html.erb, app/views/ui/inputs/_radio_field.html.erb, app/views/ui/inputs/_text_field.html.erb, app/views/ui/inputs/index.html.erb
=> input field components added

app/views/shared/components/_sidebar.html.erb
=> Partner's icon changed to user-group icon

Gemfile, Gemfile.lock, spec/value_objects/mobile_number_spec.rb
=> Update rack gem to 3.1.11

app/controllers/ui/tables_controller.rb, app/helpers/ui_helper.rb, app/views/shared/components/_table_actions.html.erb, app/views/shared/components/_table_cell_name.html.erb, app/views/shared/components/_table_cell_role.html.erb, app/views/shared/components/_table_heading.html.erb, app/views/shared/components/_table_rows.html.erb, app/views/ui/components/index.html.erb, app/views/ui/tables/index.html.erb, config/routes/ui.rb
=> Table component is created

app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/tooltip.css, app/helpers/course_modules_helper.rb, app/helpers/lessons_helper.rb, app/helpers/quizzes_helper.rb, app/helpers/ui_helper.rb, app/views/course_modules/show.html.erb, app/views/courses/show.html.erb, app/views/lessons/show.html.erb, app/views/quizzes/_quizz_box.html.erb, app/views/shared/components/_icon_button_primary.html.erb, app/views/shared/components/_outline_button_danger.html.erb, app/views/shared/components/_tooltip.html.erb, app/views/ui/buttons/_primary.html.erb, app/views/ui/buttons/_secondary.html.erb, app/views/ui/buttons/index.html.erb, config/locales/en.yml
Fixes #759, #760  
Demo: https://paulsojan.neetorecord.com/watch/864eeb16-913c-430e-a679-a60f3aca0233
=> Fixed tooltip issue

app/views/course_modules/_congrats_card.html.erb, app/views/courses/_course_lessons.html.erb, app/views/courses/_course_stats.html.erb, app/views/dashboards/index.html.erb, app/views/users/_team_user_course_status.html.erb
Renamed score to points in the dashboard and on the quiz page and all. #743
=> Label score changed to ponits

db/migrate/20250317155053_add_video_published_at_to_local_contents.rb
=> Fixed failing `AddVideoPublishedAtToLocalContents` migration

app/views/learning_partners/show.html.erb, app/views/teams/_team_actions.html.erb, config/locales/en.yml
=> Added tooltip to invite user button when disabled

app/views/shared/components/_spinner.html.erb
=> Update Spinner Border Color to primary-light

app/assets/icons/chevron-left.svg, app/assets/stylesheets/application.tailwind.css, app/assets/stylesheets/icons.css.erb, app/views/quizzes/_form.html.erb, app/views/quizzes/_quiz.html.erb, app/views/quizzes/_quiz_submit_form.html.erb, app/views/quizzes/_quizz_box.html.erb, app/views/quizzes/edit.html.erb
=> Few modifications done in quiz pages

spec/models/learning_partner_spec.rb
=> Added spec for `LearningPartner` model

app/assets/stylesheets/tooltip.css
=> Set max width to tooltip

app/assets/icons/x-circle.svg, app/assets/icons/x-mark.svg, app/assets/stylesheets/icons.css.erb, app/views/course_modules/_course_completion_quiz.html.erb, app/views/courses/_filters.html.erb, app/views/notifications/_list.html.erb, app/views/searches/_filters.html.erb, app/views/shared/components/_file_select.html.erb, app/views/shared/components/_modal.html.erb, app/views/shared/components/_modal_small.html.erb, app/views/shared/components/_notice.html.erb, app/views/shared/components/_notice_error.html.erb, app/views/shared/components/_notice_success.html.erb, app/views/shared/components/_sidebar.html.erb
=> close icone is replaced by x-circle from hero icon

app/controllers/lessons_controller.rb, app/helpers/lessons_helper.rb, app/policies/lesson_policy.rb, app/services/course_management_service.rb, app/views/lessons/_lesson.html.erb, app/views/lessons/_play_list.html.erb, app/views/lessons/show.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/lessons_spec.rb
=> Fixed the issue of lesson disables after the completed lesson is replayed 

app/controllers/lessons_controller.rb, app/helpers/lessons_helper.rb, app/views/courses/_course_lessons.html.erb, app/views/lessons/_play_list.html.erb, spec/requests/lessons_spec.rb
Fixes #824 
Demo: https://paulsojan.neetorecord.com/watch/9287e7c36a1f61895c43
=> Fixed lessons getting disabled when lesson/course module order is changed

app/views/course_modules/show.html.erb, app/views/courses/show.html.erb, app/views/lessons/_lesson.html.erb, app/views/lessons/show.html.erb, app/views/quizzes/_quizz_box.html.erb, app/views/ui/buttons/_danger.html.erb
=> Danger button component added and few other changes

app/views/courses/index.html.erb, app/views/lessons/_video_frame.html.erb, app/views/onboarding/welcomes/_welcome.html.erb, app/views/searches/_form.html.erb, app/views/searches/_selected_tags.html.erb, app/views/shared/components/_admin_not_available.html.erb, app/views/shared/components/_button_default_large.html.erb, app/views/shared/components/_button_default_small.html.erb, app/views/shared/components/_button_primary_medium.html.erb, app/views/shared/components/_button_primary_small.html.erb, app/views/shared/components/_button_secondary_outline_medium.html.erb, app/views/shared/components/_icon_button_primary.html.erb, app/views/shared/components/_icon_button_primary_small.html.erb, app/views/shared/components/_icon_button_secondary.html.erb, app/views/shared/components/_outline_button_danger.html.erb, app/views/shared/components/_outline_button_secondary.html.erb, app/views/shared/components/_outline_icon_button_primary.html.erb, app/views/shared/components/_outline_icon_button_secondary_small.html.erb, app/views/shared/components/_outline_icon_button_small.html.erb, app/views/shared/components/_table_actions.html.erb, app/views/ui/tables/index.html.erb
=> Unwanted button components from shared directry is removed

app/controllers/invites_controller.rb, app/models/user.rb, app/services/user_management_service.rb, config/routes.rb, db/migrate/20250613115755_remove_phone_verification_token.rb, db/schema.rb, spec/requests/login_with_mobile_spec.rb, spec/requests/user_invite_spec.rb
=> Remove phone verification token

app/controllers/user_settings_controller.rb, app/views/user_settings/edit.html.erb
=> Disable phone number modification

app/views/learning_partners/show.html.erb
=> Fix user listing on partner page

app/controllers/application_controller.rb, config/routes.rb, spec/requests/application_spec.rb, spec/requests/partner_onboarding_spec.rb
=> Set "Enter Mobile Number" page as Root Path

app/views/payment_plans/update.turbo_stream.erb
=> Fixed team getting undefined when updating payment plan

app/views/teams/_member_list.erb, app/views/teams/_member_list_items.html.erb, app/views/users/_user_state.html.erb
=> Add section for state unverified.

app/helpers/commons_helper.rb, app/models/learning_partner.rb, app/models/user.rb, app/policies/learning_partner_policy.rb, app/policies/user_policy.rb, app/services/user_management_service.rb, app/views/commons/_invite_user.html.erb, app/views/invites/create.turbo_stream.erb, app/views/payment_plans/update.turbo_stream.erb, app/views/quizzes/_quiz_submit_form.html.erb, app/views/users/_team_user_info.html.erb
=> Fixed active users count not updating upon inviting new user

app/controllers/application_controller.rb
=> Fixed forgot password link not working

app/models/course.rb, app/models/lesson.rb, app/services/courses/filter_service.rb, db/migrate/20250702101616_add_duration_to_courses.rb, db/schema.rb, spec/models/lesson_spec.rb, spec/requests/lessons_spec.rb
=> 894 N+1 query while computing total duration of course

app/views/courses/index.html.erb, app/views/users/show.html.erb
=> Mismatch in course progress is solved

app/views/teams/_member_list.erb, app/views/teams/_member_list_items.html.erb
team member list table is modified
=> Team member list is modified

app/helpers/application_helper.rb, app/helpers/ui_helper.rb, spec/helpers/application_helper_spec.rb, spec/helpers/ui_helper_spec.rb
Handle gracefully when nil is passed to the query_url helper by mistake.
Add tests
=> Improve the query_url helper method

app/javascript/controllers/otp_controller.js
Fixes #928 
Desktop view:
https://www.loom.com/share/02b4ddc5e60a4ed7b930e702b42e2081?sid=617cf839-20e7-42bb-ada3-c8b32f9a6173
Mobile view:
https://github.com/user-attachments/assets/b95fbd7b-a503-4571-b543-bfee052393e8
=> Add copy-paste support to OTP input fields

app/assets/stylesheets/custom.css, app/javascript/controllers/modal_loader_controller.js, app/views/shared/components/_modal.html.erb
Fixes #909 
https://www.loom.com/share/4292521bd2ce49098646500625256aa8?sid=113ac050-1014-4f9a-9928-5ac241da724d
=> loader add on top of modal,to show the progress after submition

app/controllers/teams_controller.rb, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/javascript/controllers/team_change_controller.js, app/models/team.rb, app/policies/team_policy.rb, app/policies/user_policy.rb, app/views/teams/sub_teams.turbo_stream.erb, app/views/ui/inputs/_dropdown_field.html.erb, app/views/users/_team_dropdown.html.erb, app/views/users/_team_user_info.html.erb, app/views/users/change_team.html.erb, app/views/users/confirm_change_team.turbo_stream.erb, app/views/users/show.html.erb, config/routes.rb, spec/policies/user_policy_spec.rb, spec/requests/teams_spec.rb, spec/requests/users_spec.rb
=> Implemented changing user team

app/helpers/users_helper.rb, app/views/users/_team_dropdown.html.erb
=> Fixed n+1 query in while changing user team

app/controllers/reports_controller.rb, app/helpers/application_helper.rb, app/helpers/ui_helper.rb, app/jobs/generate_report_job.rb, app/models/event.rb, app/models/report.rb, app/models/team.rb, app/models/user.rb, app/policies/report_policy.rb, app/queries/team_report_query.rb, app/services/reporting/team_report_service.rb, app/views/reports/create.turbo_stream.erb, app/views/reports/new.html.erb, app/views/reports/show.html.erb, app/views/teams/_page_header.html.erb, app/views/ui/inputs/_date_select_component.html.erb, app/views/ui/inputs/index.html.erb, app/views/ui/modals/_modal_component.html.erb, app/views/ui/typography/_linked_text_component.html.erb, app/views/ui/typography/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20250709113257_create_reports.rb, db/migrate/20250710104710_add_duration_to_reports.rb, db/migrate/20250710105051_team_and_user_to_reports.rb, db/migrate/20250710113705_add_report_type_to_reports.rb, db/schema.rb
=> Generate team reports

app/controllers/concerns/search_context_helper.rb
=> Fix assign course no method error

app/views/learning_partners/_form.html.erb, app/views/learning_partners/show.html.erb
=> Fixed not able to update learning partner about

app/views/view_components/member_list/_member_search.html.erb
=> Fixed Search input and button are touching the top edge

app/models/course_certificate.rb, app/services/courses/generate_certificate_service.rb, config/storage.yml
=> Specify public bucket in storage.yml

app/controllers/courses_controller.rb, app/services/courses/filter_service.rb
=> Fixes courses count (#1043)

config/tailwind.config.js
=> White-light color code is changed

app/views/courses/index.html.erb, app/views/searches/_form.html.erb, app/views/view_components/course_select/_search_component.html.erb, config/tailwind.config.js
=> Removed purple and used primary-light instead
