openvitae-tech/blackboard-lms

- app/views/settings/_show_desktop.html.erb
- app/views/settings/_show_mobile.html.erb
- app/views/shared/components/_button_default_small.html.erb
- app/views/shared/components/_edit_button.html.erb
Edit buttons issue is resolved when we resets minimum height and width ,now just removed an unwanted class(item-center) from the span tag which is used to show the edit icon
> Unwanted class fro edit button's icon has been removed

- app/views/teams/_form.html.erb
In Team add modal, "upload team banner" label text had some fixes with in the instruction (file size should be less than 1MB) also some styles added to it
> Team add modal upload team banner label text fixes

- app/views/shared/components/_course_card_with_left_image.html.erb
- app/views/shared/components/_course_description_card.html.erb
Course headline in "italic" where reverted to normal ,also course card with left image where having a border and it is replaced with box shadow and hover effect added by border border-line-color
Fixes #90
> Course headline correctons

- app/views/learning_partners/index.html.erb
Arrow link was not having the link path ,so added the path .
Both clicking on arrow and the partner name will take to the partners page.
Fixes #154
> On partners list arrow link was not working when clicking

- app/assets/stylesheets/course.css.erb
- app/views/courses/_course_description_card.html.erb
- app/views/courses/_course_description_card_mobile.html.erb
Course Description and course banner made to be  on the same line, also curves on the left corners of the banner is removed
Fixes #275
> Course banner and description box made to  ends on the same line

- app/views/teams/_team_desktop.html.erb
On the teams list, the arrow was not properly aligned 
Fixes #277
> teams list fixes

- app/views/courses/_course_lessons.html.erb
Mis alignment in the default open item is solved
Fixes #324
> Mis alignment in the default open item is resolved

- app/views/course_assigns/_new_desktop.html.erb
- app/views/course_assigns/_new_mobile.html.erb
- app/views/courses/_show_desktop.html.erb
- app/views/courses/_show_mobile.html.erb
Add missing back button in the course details page 
Fixes #372
> Backbutton at course

- app/views/shared/components/_navbar.html.erb
while scrolling icons and some components where moving above nav bar and fixed now
Fixes #467
the issue looks like in the image 
now fixed
> z index fixed for nav bar

- app/views/courses/_course_card_with_top_image.html.erb
inconsistent spacing in text while showing course card.
Fixes  #419
> inconsistent spacing in text while showing course card is solved

- app/controllers/local_contents_controller.rb
- app/helpers/lessons_helper.rb
- app/services/vimeo/upload_video_service.rb
- app/views/lessons/_video_frame.html.erb
Fixes #472 
This will enable the `retry upload` button even if the Vimeo public URL is not found in the blob metadata.
> Enabled retry upload button if uploaded video vimeo url is not found in blob metadata

- app/views/shared/components/_sidebar.html.erb
In the new layout the logo is stretched and blurred 
Fixes #488
> Sidebar logo strecthing issue fixed

- app/views/shared/components/_flash.html.erb
- app/views/shared/components/_layout.html.erb
- app/views/tags/_tag.html.erb
- app/views/tags/edit.html.erb
- app/views/tags/index.html.erb
- app/views/tags/new.html.erb
Tags page is moved to single layout 
Fixes #505
> Tags page in single layout 

- app/views/shared/components/_sidebar.html.erb
Support tag was not getting selected when it is clicked like other tags getting selected is solved
Fixes #520
> Support tag at side bar not getting selected is solved

- app/views/shared/components/_sidebar.html.erb
- app/views/user_settings/show.html.erb
The logout link was  missing in firefox so logout link moved to user settings page 
Fixes #546
> Logout moved to user settings page

- app/views/dashboards/index.html.erb
- app/views/learning_partners/index.html.erb
- app/views/learning_partners/show.html.erb
- app/views/settings/index.html.erb
- app/views/tags/index.html.erb
All headings are aligned from the same distance from the nav bar
Fixes  #571
> Standardized top margin for all headings

- app/views/course_assigns/_course_card.html.erb
- app/views/course_assigns/new.html.erb
- app/views/teams/_team_card.html.erb
Assign page heading and assign duration text  font changed to Poppins
Fixes  #633
Sub team title in the card  changed to font Poppins 
Fixes #634
> Some missing font changes to poppins

- app/views/course_modules/show.html.erb
- config/locales/en.yml
> Fixed button alignment issue in course modules page

- .husky/helpers/no_console.sh
- .husky/pre-commit
> Fixed `no_console` script fails if no JS files found in the staged files

- app/views/searches/_filters.html.erb
- app/views/searches/_form.html.erb
Filter tab not starting from the top right after the nav bar issue resolved
Fixes #659
> Fix Filter tab positioning to align with the top right after the navbar

- app/views/course_modules/_form.html.erb
- app/views/course_modules/edit.html.erb
- app/views/course_modules/new.html.erb
- app/views/courses/_form.html.erb
- app/views/courses/edit.html.erb
- app/views/courses/new.html.erb
- app/views/learning_partners/_form.html.erb
- app/views/learning_partners/edit.html.erb
- app/views/learning_partners/new.html.erb
- app/views/learning_partners/show.html.erb
- app/views/lessons/_form.html.erb
- app/views/lessons/edit.html.erb
- app/views/lessons/new.html.erb
- app/views/quizzes/_form.html.erb
- app/views/quizzes/edit.html.erb
- app/views/quizzes/new.html.erb
fixes #789
Fixed alignment of form pages while maintaining width consistency
Previously, form pages were centered with free space on both sides, while normal pages were full-width.
Now, the form pages remain the same width but are left-aligned instead of centered.
This ensures the back button stays in the same position for a more consistent user experience.
https://www.loom.com/share/b16882a1e735424185bbcb4983852aed?sid=244ad077-4b65-4ea2-b0be-fb1bb56307ff
> Fixed page width inconsistency in courses and learning partners  admin pages

- app/views/shared/components/_more_action.html.erb
Added a higher z-index to the dropdown container.
Fixes #810
> resolve dropdown overlap with partner title using z-50

- app/views/learning_partners/show.html.erb
- app/views/teams/_member_list.erb
- app/views/teams/_member_list_items.html.erb
- app/views/teams/all_users.html.erb
- app/views/teams/show.html.erb
Removed conditional height_class logic from the partial.
Applied a flex flex-col layout structure.
Header section is now fixed using flex-shrink-0.
Member list content scrolls using flex-1 overflow-y-auto.
Height is now fully controlled from the calling view (e.g. max-h-[400px], max-h-[750px]).
Fixes #813
> Refactor member_list partial to support scrollable layout via outer height wrapper

- app/helpers/ui_helper.rb
- app/views/course_modules/_course_completion_quiz.html.erb
- app/views/course_modules/_summary.html.erb
- app/views/course_modules/show.html.erb
- app/views/course_modules/summary.html.erb
- app/views/courses/_course_description_card.html.erb
- app/views/courses/_course_lessons.html.erb
- app/views/courses/index.html.erb
- app/views/courses/show.html.erb
- app/views/invites/new.html.erb
- app/views/lessons/_lesson.html.erb
- app/views/lessons/add_edit/_add_local_content.html.erb
- app/views/lessons/add_edit/_edit_local_content.html.erb
- app/views/lessons/show.html.erb
- app/views/quizzes/_quizz_box.html.erb
- app/views/teams/_form.html.erb
- app/views/ui/buttons/_primary.html.erb
- app/views/ui/buttons/_secondary.html.erb
Buttons in courses pages are replaced with button components
> Buttons in Course pages view changed to button components

- app/views/learning_partners/index.html.erb
- app/views/teams/_sub_teams.html.erb
Few Buttons were missed out to change into button components in teams page and partners page and it is replaced with button components
> Missed Buttons in partners and teams view changed to button components

- app/views/tags/_tag.html.erb
- app/views/tags/index.html.erb
- app/views/user_settings/_page_body.html.erb
Remaining buttons in tags page and user page is replaced with button components
> Buttons in tags page and other remaining buttons are replaced with button components

- app/assets/stylesheets/tooltip.css
- app/views/shared/components/_tooltip.html.erb
Fixes : #935
Replaced data-tooltip-target="<%= tooltip_position %>" with tooltip-<%= tooltip_position %> class to avoid JavaScript errors like The tooltip element with id "bottom" does not exist. This change also simplifies tooltip positioning logic by moving it entirely to class-based CSS selectors (e.g., .tooltip.tooltip-left).
> Fixed Tooltip element ID error caused by the use of data-tooltip-target 

- app/javascript/controllers/otp_controller.js
- app/views/logins/_otp_desktop.html.erb
- app/views/logins/_otp_mobile.html.erb
Verify button remained disabled even when all OTP fields were filled.
- Calls updateButtonState() inside updateHiddenOtp() to ensure the button state updates on all input changes.
- Adds input keydown and change event listeners to each OTP input to reliably capture user interactions across different devices and keyboards.
> Fix OTP verify button state update for all input scenarios

- app/helpers/ui_helper.rb
- app/javascript/controllers/vimeo_controller.js
- app/views/lessons/_lesson.html.erb
- app/views/ui/buttons/_danger.html.erb
- app/views/ui/buttons/_primary.html.erb
- app/views/ui/buttons/_secondary.html.erb
- Applied conditional styling: bg-secondary when disabled, bg-primary when enabled
- Updated the `button` component to support `html:` option for passing HTML attributes
> Enhance Complete and Continue button state styling and HTML options

- app/helpers/dashboards_helper.rb
- app/value_objects/dashboard.rb
- app/views/dashboards/_average_time_spend_chart.html.erb
- app/views/dashboards/_self_enrolled_vs_assigned_chart.html.erb
- app/views/dashboards/_total_views_chart.html.erb
- app/views/dashboards/_users_enrolled.html.erb
Refactored the chart series scaling logic to be reusable for all dashboard charts.  
If a series exceeds its configured max value, it is scaled down proportionally so that it fits the chart area while preserving relative differences between data points.  
This now works for multiple charts, including Time Spent, Course Started, Course Completed, and Users Enrolled.
> Make dashboard chart series scaling reusable with configurable max values

- app/javascript/application.js
- app/javascript/utils/js_warning.js
- app/views/layouts/application.html.erb
- Added event listeners for `turbo:load` and `turbo:render` in addition to `DOMContentLoaded`.  
- This ensures the banner is always hidden, both on initial load and during subsequent Turbo navigations or form submissions.
https://www.loom.com/share/6df7720ed4b045d3aac5020e75d85d7a?sid=7bb47d88-a577-4e14-a0e9-b60f92c9933b
https://www.loom.com/share/12979c1122f6451895ac12c590f9d79a?sid=9de90d1b-1033-4a1f-a077-ca0ceca8a3d2
> ensure JS not loaded banner is hidden on all Turbo navigations

- app/services/courses/generate_certificate_service.rb
Added  option in Grover PDF generation to render certificates in landscape orientation.
> Enable landscape orientation for generated PDFs

- app/views/lessons/_play_list.html.erb
> Fix progress bar contrast in highlighted lesson modules
